// Sample data to load when localStorage is empty
export const getSampleTasks = () => {
  return [
    {
      id: "sample-1",
      ticketNumber: "TICKET-001",
      statusInternal: "validating",
      statusExternal: "in progress",
      todo: "yes-priority",
      rank: "high",
      notes: "Need to verify API integration",
      askedTo: "John Doe",
      askedToStatus: "pending",
      lastUpdated: "01/12/2024, 10:30",
      tags: ["backend", "api"],
    },
    {
      id: "sample-2",
      ticketNumber: "TICKET-002",
      statusInternal: "waiting-external",
      statusExternal: "WFC",
      todo: "yes",
      rank: "normal",
      notes: "Waiting for client feedback",
      askedTo: "Client Team",
      askedToStatus: "pending",
      lastUpdated: "02/12/2024, 14:20",
      tags: ["client", "feedback"],
    },
    {
      id: "sample-3",
      ticketNumber: "TICKET-003",
      statusInternal: "resolved",
      statusExternal: "resolved",
      todo: "no",
      rank: "normal",
      notes: "Issue fixed and deployed",
      askedTo: "Dev Team",
      askedToStatus: "done",
      lastUpdated: "03/12/2024, 09:15",
      tags: ["deployment", "bugfix"],
    },
    {
      id: "sample-4",
      ticketNumber: "TICKET-004",
      statusInternal: "waiting-internal",
      statusExternal: "in progress",
      todo: "yes-priority",
      rank: "high",
      notes: "Need internal review",
      askedTo: "QA Team",
      askedToStatus: "pending",
      lastUpdated: "04/12/2024, 11:45",
      tags: ["testing", "review"],
    },
    {
      id: "sample-5",
      ticketNumber: "TICKET-005",
      statusInternal: "new",
      statusExternal: "new",
      todo: "yes",
      rank: "normal",
      notes: "New feature request",
      askedTo: "Product Team",
      askedToStatus: "pending",
      lastUpdated: "05/12/2024, 16:00",
      tags: ["feature", "enhancement"],
    },
    {
      id: "sample-6",
      ticketNumber: "TICKET-006",
      statusInternal: "resolved-wfc",
      statusExternal: "resolved",
      todo: "no",
      rank: "normal",
      notes: "Resolved waiting for confirmation",
      askedTo: "Client Team",
      askedToStatus: "done",
      lastUpdated: "06/12/2024, 13:30",
      tags: ["client", "confirmation"],
    },
  ];
};

